### ISSUE TITLE
Code convension

### ISSUE THREAD

**Issue by shramko82** [KatiaBatura/KatiaBatura.github.io#2]
Please, follow the code convension in naming variables.
http://www.w3schools.com/js/js_conventions.asp

**Comment by NadiiaSkrupska** [comment]
Done, will be totally implemented in future projects

**Comment by KatiaBatura** [comment]
ok. I have already read this article

**Comment by shramko82** [comment]
But you still use variable UserName
please, change it to userName

**Comment by KatiaBatura** [comment]
done
