### ISSUE TITLE
Remove redundant code (lesson 2; ex. 4, 5)

### ISSUE THREAD

**Issue by shramko82** [KatiaBatura/KatiaBatura.github.io#5]
You dont need a variable for this:

    var result=(a + b >= 3)? 'Yep!': 'Noup!';
    alert(result);

Please, rewrite it without using a variable 'result'

**Comment by NadiiaSkrupska** [comment]
I don't relly get what to change in Task 2.5, so I just removed variable text from var ad added var before text. For 2.4: done

**Comment by KatiaBatura** [comment]
I don't understand how it rewrite

**Comment by shramko82** [comment]
I wanted to see thomething like

    console.log((a + b >= 3) ? 'Yep!' : 'Noup!');

**Comment by KatiaBatura** [comment]
ok, I changed
